# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Weekly Journal"
  url = "/journal"
  weight = 20

[[main]]
  name = "Knowledge Center"
  url = "/knowledge-center"
  weight = 30

[[main]]
  name = "Community"
  url = "/community"
  weight = 40

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 50

[[main]]
  parent = "Knowledge Center"
  name = "Overview"
  url = "/knowledge-center"
  weight = 10

[[main]]
  parent = "Knowledge Center"
  name = "(Visual) collaboration"
  url = "/knowledge-center/collaboration"
  weight = 20

[[main]]
  parent = "Knowledge Center"
  name = "Engineering culture"
  url = "/knowledge-center/engineering-culture"
  weight = 20

[[main]]
  parent = "Knowledge Center"
  name = "Organisational design"
  url = "/knowledge-center/organisational-design"
  weight = 20

[[main]]
  parent = "Knowledge Center"
  name = "Socio-technical systems"
  url = "/knowledge-center/socio-technical"
  weight = 20

[[main]]
  parent = "Knowledge Center"
  name = "Software architecture"
  url = "/knowledge-center/software-architecture"
  weight = 20